### ISSUE TITLE
holidays' calls async_forward_entry_setup for integration, holidays with title: Holidays CZ and entry_id: 16bfc13d77336b661053daa0ea924bed, which is deprecated and will stop working in Home Assistant 2025.6

### ISSUE THREAD

**Issue by Hadatko** [bruxy70/Holidays#62]
### Before you submit a new bug report, please check that

- [X] I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
- [X] I'm running the newest version of Holidays, or the next pre-release.
- [X] I have enabled debug logging for my installation.

### Describe the bug

Warning thrown by HA

### Configuration

```JSON
i am not able.
```

### Debug logs

```shell
log from HA:

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:184
First occurred: 8:38:21 AM (2 occurrences)
Last logged: 8:38:41 AM

Detected that custom integration 'holidays' calls async_forward_entry_setup for integration, holidays with title: Holidays CZ and entry_id: 16bfc13d77336b661053daa0ea924bed, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/holidays/__init__.py, line 40: hass.async_create_task(, please create a bug report at https://github.com/bruxy70/Holidays/issues
```

**Comment by L81ker** [comment]
Same bug noticed., similar error logs

2024-09-01 08:46:01.749 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'holidays' calls async_forward_entry_setup for integration, holidays with title: UK Public Holiday Calendar  and entry_id: 01J59CRS0H76NVP3QT4HBRXVAA, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/holidays/__init__.py, line 40: hass.async_create_task(, please create a bug report at https://github.com/bruxy70/Holidays/issues
2024-09-01 08:46:02.777 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration holidays with title: UK Public Holiday Calendar  and entry_id: 01J59CRS0H76NVP3QT4HBRXVAA, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2161, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1201, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 151, in report
    _LOGGER.warning(msg, stack_info=True)

**Comment by myTselection** [comment]
PR in #65 for this

**Comment by L81ker** [comment]
waiting for this bug to be fixed. Any updates?

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:380
First occurred: 12:46:02 (1 occurrence)
Last logged: 12:46:02

Detected code that calls async_forward_entry_setup for integration holidays with title: UK Public Holiday Calendar and entry_id: 01J59CRS0H76NVP3QT4HBRXVAA, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1, please report this issue

**Comment by JimRnewell** [comment]
Same issue:
Error setting up entry Bank Holidays for holidays
Error setting up entry holidays for holidays
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/holidays/__init__.py", line 41, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
